apiVersion: v1
kind: Pod
metadata:
  name: tutorial-pod
spec:
  containers:
  - name: gpu-container
    image: dhbhatt/rainbow-demorl:latest
    command: ["/bin/bash", "-c", "sleep 21600"]
    volumeMounts:
    - mountPath: /nikola_volume
      name: nikola-volume
    resources:
      limits:
        nvidia.com/gpu: "1"
        memory: "8G"
        cpu: "4"
  restartPolicy: Never
  volumes:
    - name: nikola-volume
      persistentVolumeClaim:
        claimName: nikola-volume
